build:
name: Build with CMake
needs: clang-format-check
runs-on: ubuntu-latest
strategy:
matrix:
build-type: [Debug, Release]
steps:
- uses: actions/checkout@v4
- name: Install dependencies
run: |
sudo apt-get update
sudo apt-get install -y build-essential cmake
- name: Configure CMake
run: |
cmake -B build -DCMAKE_BUILD_TYPE=$
{{ matrix.build-type }} -DBUILD_TESTS=ON
- name: Build project
run: cmake --build build --config $
{{ matrix.build-type }}
- name: Upload build artifacts
uses: actions/upload-artifact@v4
with:
name: build-${{ matrix.build-type }}
path: build/
retention-days: 1
