name: Build with CMake

on: [push, pull_request]

jobs:
  build:
    name: Build with CMake
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [gcc, clang]
        os: [ubuntu-latest, windows-latest]
        build-type: [Debug, Release]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ninja
      
      - name: Configure CMake
        shell: bash  # Явно указываем использовать bash для кросс-платформенности
        run: |
          echo "Current directory: $(pwd)"
          ls -la  # Для отладки
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DBUILD_TESTS=ON \
            ${{ matrix.os == 'windows-latest' && '-G "Ninja"' || '' }}
      
      - name: Build project
        run: cmake --build build --config ${{ matrix.build-type }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.build-type }}
          path: build/
          retention-days: 1
